#!/usr/bin/env python3
import os
import subprocess
import urllib.parse
from datetime import datetime, timezone
from pathlib import Path


def get_repo():
    env = os.environ.get("GITHUB_REPOSITORY")
    if env:
        return env
    try:
        url = subprocess.check_output(
            ["git", "remote", "get-url", "origin"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return "your-username/team-portfolio"

    if url.startswith("git@"):
        url = url.replace(":", "/", 1).replace("git@", "https://", 1)
    if url.endswith(".git"):
        url = url[:-4]
    if "github.com/" in url:
        return url.split("github.com/", 1)[1]
    return "your-username/team-portfolio"


REPO = get_repo()
BRANCH = os.environ.get("GITHUB_REF_NAME", "main")
ROOT = Path(".")

SCAN_DIRS = [
    "project-proposal",
    "docs/00-governance",
    "docs/01-research-upskilling",
    "docs/02-planning-control",
    "docs/03-communication-teamwork",
    "docs/04-development-qa",
    "logbook",
]

IGNORE_DIRS = {".git", ".github", "scripts", "archive", "node_modules", "__pycache__"}
IGNORE_FILES = {"index.html", ".DS_Store", ".nojekyll"}

SHOW_EXTS = {
    ".md", ".html", ".pdf", ".png", ".jpg", ".jpeg", ".svg",
    ".csv", ".txt", ".drawio", ".json", ".yml", ".yaml",
}


def is_visible(path: Path) -> bool:
    if any(part in IGNORE_DIRS for part in path.parts):
        return False
    if path.name in IGNORE_FILES:
        return False
    if path.name.startswith("."):
        return False
    return path.suffix.lower() in SHOW_EXTS


def github_url(path: Path, is_dir: bool = False) -> str:
    kind = "tree" if is_dir else "blob"
    quoted = urllib.parse.quote(str(path).replace("\\", "/"))
    return f"https://github.com/{REPO}/{kind}/{BRANCH}/{quoted}"


def collect_files(base: str):
    base_path = ROOT / base
    if not base_path.exists():
        return []
    return [
        p for p in sorted(base_path.rglob("*"))
        if p.is_file() and is_visible(p)
    ]


def render_section(title: str, files):
    if not files:
        return f"<h2>{title}</h2><p>No files yet.</p>"
    items = []
    for f in files:
        rel = f.relative_to(ROOT)
        url = github_url(rel, is_dir=False)
        display = str(rel).replace("\\", "/")
        items.append(f'<li><a href="{url}">{display}</a></li>')
    return f"<h2>{title}</h2>\n<ul>\n" + "\n".join(items) + "\n</ul>"


def main():
    sections = []

    readme = ROOT / "README.md"
    if readme.exists():
        sections.append(f'<p><a href="{github_url(readme)}">README.md</a></p>')

    for d in SCAN_DIRS:
        files = collect_files(d)
        sections.append(render_section(d, files))

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Team Portfolio Navigation</title>
<style>
  body {{ font-family: system-ui, -apple-system, "Segoe UI", sans-serif; max-width: 1000px; margin: 2rem auto; padding: 0 1rem; line-height: 1.6; color: #24292f; }}
  h1 {{ border-bottom: 1px solid #d0d7de; padding-bottom: .3rem; }}
  h2 {{ margin-top: 2rem; border-bottom: 1px solid #d0d7de; padding-bottom: .2rem; }}
  ul {{ list-style: none; padding-left: 0; }}
  li {{ margin: .3rem 0; }}
  a {{ color: #0969da; text-decoration: none; }}
  a:hover {{ text-decoration: underline; }}
  .meta {{ color: #57606a; font-size: .9rem; }}
</style>
</head>
<body>
<h1>Team Portfolio Navigation</h1>
<p class="meta">Last auto-update: {now}</p>
<p>This page is automatically generated by GitHub Actions. After adding new files, wait for the Action to complete and refresh the page.</p>
{''.join(sections)}
</body>
</html>
"""
    (ROOT / "index.html").write_text(html, encoding="utf-8")
    print("index.html generated")


if __name__ == "__main__":
    main()
